#!/bin/bash
git clone https://github.com/jfsicilia/bclose.git ~/.vim/pack/plugins/start/bclose &&
git clone https://github.com/tpope/vim-fugitive.git ~/.vim/pack/plugins/start/vim-fugitive &&
git clone https://github.com/preservim/nerdtree.git ~/.vim/pack/plugins/start/nerdtree &&
git clone https://github.com/SirVer/ultisnips.git ~/.vim/pack/plugins/start/ultisnips &&
git clone https://github.com/vim-airline/vim-airline.git ~/.vim/pack/plugins/start/vim-airline &&
git clone https://github.com/vim-airline/vim-airline-themes.git ~/.vim/pack/plugins/start/vim-airline-theme &&
git clone https://github.com/evansalter/vim-checklist.git ~/.vim/pack/plugins/start/vim-checklist &&
git clone https://github.com/tpope/vim-commentary.git ~/.vim/pack/plugins/start/vim-commentary &&
git clone https://github.com/pangloss/vim-javascript.git ~/.vim/pack/plugins/start/vim-javascript &&
git clone https://github.com/sheerun/vim-polyglot.git ~/.vim/pack/plugins/start/vim-polyglot &&
git clone https://github.com/garbas/vim-snipmate.git ~/.vim/pack/plugins/start/vim-snipmate &&
git clone https://github.com/tpope/vim-surround.git ~/.vim/pack/plugins/start/vim-surround
